---
deployment:
  tasks:
    - export DEPLOYPATH=/home/utsavkaf/repositories/portfolio
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp tailwind.config.js
